name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pillow PyQt5

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py') \
            --extension-pkg-whitelist=PyQt5 \
            --disable=import-error,no-name-in-module,unused-import,too-many-instance-attributes,missing-class-docstring,broad-exception-caught,invalid-name,wrong-import-order
